### ISSUE TITLE
Bootstrap nav created with d3 and data

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/d3-playground#61]
- [source](https://github.com/bigdata-mindstorms/d3-playground/tree/gh-pages/ontouchstart/2016/03/16)
- [test](https://bigdata-mindstorms.github.io/d3-playground/ontouchstart/2016/03/16/nav.html)

![image](https://cloud.githubusercontent.com/assets/951921/13821708/17b750e4-eb79-11e5-94ef-6d4daf9d99d3.png)

![image](https://cloud.githubusercontent.com/assets/951921/13821715/1ec7d5a2-eb79-11e5-84bd-277fa94993bb.png)

**Comment by LivingProgram** [comment]
I have a couple questions:
* where do these attributes come from? and can you make your own? what does it do?
```javascript
      .attr('data-toggle', 'collapse')
      .attr('data-target', '#navbar')
      .attr('aria-expanded', 'false')
      .attr('aria-controls', 'navbar');
```
* what is the `span` in a button? what does it do?
* where do these classes come from? what does it do?
```javascript
  button.append('span').attr('class', 'sr-only').html('Toggle navigation');
  button.append('span').attr('class', 'icon-bar');
  button.append('span').attr('class', 'icon-bar');
  button.append('span').attr('class', 'icon-bar');  
```

**Comment by LivingProgram** [comment]
https://github.com/bigdata-mindstorms/d3-playground/tree/gh-pages/LivingProgram/2016/03/28

**Comment by ontouchstart** [comment]
How about reading the source and write up what your learn in a new tutorial?

https://github.com/twbs/bootstrap/tree/master/less

( If you do not know what LESS is, google it :smile: )

**Comment by LivingProgram** [comment]
## What is LESS?
LESS is a CSS pre-processor, meaning that it extends the CSS language, adding features that allow variables, mixins, functions and many other techniques that allow you to make CSS that is more maintainable, themable and extendable.

In simple terms, LESS allows you to write CSS in a smarter way by combining functions, mixins, operations and more. This means you write more concise style information and can reuse things like colors and styles more easily. 

> Remember: Cascading Style Sheets (CSS) are a stylesheet language used to describe the presentation of a document written in HTML. CSS describes how elements should be rendered on screen, on paper, in speech, or on other media.

**Comment by LivingProgram** [comment]
## Basic CSS Syntax
Learn it [here](http://www.w3schools.com/css/css_syntax.asp), if you have any questions post below so we can improve the explanation.

**Comment by LivingProgram** [comment]
I will post a short guide on less css later (using [this](http://www.hongkiat.com/blog/less-basic/) as a guide to less, and [this](http://www.hongkiat.com/blog/less-color-functions/) for less color functions)

**Comment by ontouchstart** [comment]
@LivingProgram 

Don't jump in too quickly, [Bootstrap 4 is going to switch to SASS](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/).

Now you can google SASS. :wink: 

Seriously, do not waste your time on these unless you have to do it because your boss is just chasing the latest fad. Understand the basic concept is more important than [syntactic sugar](https://en.m.wikipedia.org/wiki/Syntactic_sugar).

**Comment by LivingProgram** [comment]
## Less Variables
The variables will allow us to store a constant value that later can be reused in the entire stylesheet.
```less
@color-base: #2d5e8b;
 
.class1 {
    background-color: @color-base;
}
.class2 {
    background-color: #fff;
    color: @color-base;
}
.class3 {
    border: 1px solid @color-base;
}
```
More Examples:
```less
@font-family: Georgia
@dot-border: dotted
@transition: linear
@opacity: 0.5
```

**Comment by LivingProgram** [comment]
## Less Mixins
We can use Mixins to reuse whole declarations in a CSS rule set in another rule set. Here is an example: (almost like a block of code that can be inserted, or a variable that holds multiple values)

This is a mixin:
```less
.gradients {
    background: #eaeaea; 
    background: linear-gradient(top, #eaeaea, #cccccc);
    background: -o-linear-gradient(top, #eaeaea, #cccccc); 
    background: -ms-linear-gradient(top, #eaeaea, #cccccc); 
    background: -moz-linear-gradient(top, #eaeaea, #cccccc); 
    background: -webkit-linear-gradient(top, #eaeaea, #cccccc); 
}
```
Here is it used in a div:
```less
div {
    .gradients;
    border: 1px solid #555;
    border-radius: 3px;
}
```
So after compiling you end up with:
```less
div {
    background: #eaeaea; 
    background: linear-gradient(top, #eaeaea, #cccccc);
    background: -o-linear-gradient(top, #eaeaea, #cccccc); 
    background: -ms-linear-gradient(top, #eaeaea, #cccccc); 
    background: -moz-linear-gradient(top, #eaeaea, #cccccc); 
    background: -webkit-linear-gradient(top, #eaeaea, #cccccc); 
    border: 1px solid #555;
    border-radius: 3px;
}
```

**Comment by LivingProgram** [comment]
## LESS Elements
LESS Elements is a collection of common CSS3 Mixins that we may use often in stylesheets, such as `border-radius`, `gradients`, `drop-shadow` and so on.

For example: 
> To add a 3px border to a div
```less
div {
    .rounded(3px);
}
```

For the official documentation go [here](http://lesselements.com/)

**Comment by LivingProgram** [comment]
## Nested Rules 
In LESS CSS, we can simplify the rule sets by **nesting the child elements inside the parents**, so this way you don't have to repeat the parents every time you call for a child.

Here is what you would have to do in CSS:
```less
nav {
    height: 40px;
    width: 100%;
    background: #455868;
    border-bottom: 2px solid #283744;
}
nav li {
    width: 600px;
    height: 40px;
}
nav li a {
    color: #fff;
    line-height: 40px;
    text-shadow: 1px 1px 0px #283744;
}
```

But with LESS you can nest them like below:
```less
nav {
    height: 40px;
    width: 100%;
    background: #455868;
    border-bottom: 2px solid #283744;
    li {
        width: 600px;
        height: 40px;
        a {
            color: #fff;
            line-height: 40px;
            text-shadow: 1px 1px 0px #283744;
        }
    }
}
```

#### Pseudo-classes
> A [pseudo-class](http://www.w3schools.com/css/css_pseudo_classes.asp) is used to define a special state of an element.
For example, it can be used to:
* Style an element when a user mouses over it
* Style visited and unvisited links differently
* Style an element when it gets focus

You can also assign pseudo-classes, like :hover, to the selector using the ampersand (&) symbol.
For example (you want background and color to change when the user hovers over the element
```less
a {
    color: #fff;
    line-height: 40px;
    text-shadow: 1px 1px 0px #283744;
    &:hover {
        background-color: #000;
        color: #fff;
    }
}
```

**Comment by LivingProgram** [comment]
## Less Operation
We can also perform operations in LESS, such as addition, subtraction, multiplication and division to numbers, colors and variables in the stylesheet.

Here we have element B to be two times higher than element A
```less
@height: 100px
 
.element-A {
    height: @height;    
}
.element-B {
    height: @height * 2;
}
```
> What is the purpose?
That means you can define elements in relativity to each other without doing the math yourself!

**Comment by LivingProgram** [comment]
## Scope Concept
LESS applies the Scope concept, where variables will be inherited first from the local scope, and when it is not available locally, it will search through a wider scope.
Example:
```less
header {
    @color: black;
    background-color: @color;
    nav {
        @color: blue;
            background-color: @color;
        a {
                color: @color;
        }
    }
}
```
In the example above, the `header` has a black background color, but `nav`‘s background color will be blue as it has the `@color` variable in its local scope, while the `a` will also have blue that is inherited from its nearer parent, `nav`.
